# Fichier de configuration pour lancer les services en local pour le dev

version: '3.8'

name: sae-backend-dev

services:

  db:
    image: postgres:15-alpine
    restart: unless-stopped
    command: postgres -c 'max_connections=1000' -c 'shared_buffers=80MB'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - sae-backend-dev-data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"

  admin:
    image: adminer:latest
    restart: unless-stopped
    ports:
      - "8090:8080"
    depends_on:
      - db

volumes:
  sae-backend-dev-data:
